# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://www.cathaybk.com.tw/cathaybk")
    assert self.driver.title == "國泰世華銀行"
    self.driver.set_window_size(1552, 840)
    self.driver.get_screenshot_as_file("screenshot.png")
    self.driver.find_element(By.LINK_TEXT, "開戶").click()
    self.driver.get_screenshot_as_file("screenshot.png")
    self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-next > p").click()
    self.driver.get_screenshot_as_file("screenshot.png")
    self.driver.find_element(By.LINK_TEXT, "下載CUBE App").click()
    self.driver.get_screenshot_as_file("screenshot.png")
    self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-next > p").click()
    android = self.driver.find_element(By.ID, "android").text
    ios = self.driver.find_element(By.ID, "ios").text
    if android != ios :
        print("CUBE App Android與iOS版本不一致")
  
